spring:
  application:
    name: app
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      format_sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    root: WARN
    org.springframework: INFO
    hexlet.code.app: DEBUG
    io.sentry: DEBUG  # Детальные логи Sentry

server:
  address: 0.0.0.0

sentry:
  dsn: ${SENTRY_DSN}
  debug: true
  send-default-pii: false
  traces-sample-rate: 1.0
